title = "LibreSCRS"
languageName = "Српски"
weight = 2

[params]
  description = "Читач смарт картица и дигитално потписивање отвореног кода — било која картица, било која платформа"

  [params.author]
    name = "LibreSCRS пројекат"
    links = [
      {github = "https://github.com/LibreSCRS"}
    ]
