[[main]]
  name = "Преузимања"
  pageRef = "downloads"
  weight = 10

[[main]]
  name = "Документација"
  pageRef = "docs"
  weight = 20

[[main]]
  name = "О пројекту"
  pageRef = "about"
  weight = 30

[[main]]
  identifier = "search"
  weight = 40
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 50
  [main.params]
    action = "locale"

[[main]]
  identifier = "appearance"
  weight = 60
  [main.params]
    action = "appearance"
